### ISSUE TITLE
Try to augment entities with data from Wikipedia

### ISSUE THREAD

**Issue by pudo** [pudo/opensanctions#1]
This could be a possible way of getting access to family and close associates. 

Also have to check out what Dima did: https://github.com/dchaplinsky/pep.org.ua/blob/8633a65fb657d7f04dbdb12eb8ae705fa6be67e3/pepdb/tasks/management/commands/match_to_wiki.py

**Comment by AndreiD** [comment]
looking for something similar...

**Comment by pudo** [comment]
@AndreiD look no further :) https://www.opensanctions.org/datasets/wd_curated/

**Comment by pudo** [comment]
Closing this: the import is there, just need to be able to run the enrichment pipeline on existing entities now.
