### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 2)

### ISSUE THREAD

**Issue by francofabio** [pudo/opensanctions#101]
I'm  trying load the OpenSanctions JSON-model but I'm receiving this error `json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 2)`

I'm using the command `cat opensanctions.json | ftm store write -d opensanctions`

Would you guys help me to understand what's going on?

**Comment by pudo** [comment]
Hmm, that sounds like some broken JSON. Can you tell me what `opensanctions.json` is and where you got it?

**Comment by francofabio** [comment]
@pudo I got the `opensanctions.json` on opensanctions.org

**Comment by pudo** [comment]
Ah, I assume you downloaded the index file (https://data.opensanctions.org/datasets/latest/index.json). Try using one of the collections:

* All data: https://data.opensanctions.org/datasets/latest/all/entities.ftm.json
* All sanctions: https://data.opensanctions.org/datasets/latest/sanctions/entities.ftm.json

Can't wait till I have finished the home page :)

**Comment by francofabio** [comment]
Wow! Thank you so much @pudo 
I will try it
