### ISSUE TITLE
Adding a new source from the source survey 2021 gsheet

### ISSUE THREAD

**Issue by quantumchips** [pudo/opensanctions#125]
Hello team. I'd like to contribute to this project by starting with the first row in [this](https://docs.google.com/spreadsheets/d/1zHP91a-KT-MW-3s2Xb9-wPVhxTiPO1ZqJ90v4COswRY/edit#gid=0) sheet. This is my first time contributing to OS so any guidance/feedback is appreciated!

**Comment by pudo** [comment]
Very cool, Ary, welcome! You're digging into the ZA police service, then? The sheet is a bit randomly sorted, but that one should be easy enough! Have you seen the docs at https://docs.opensanctions.org/en/latest/crawlers.html ? Let me know how it goes!

**Comment by quantumchips** [comment]
Thanks! Yeah I just randomly picked the first one. I'm new to coding (although I know my way around Python) so I'm still trying to make sense of the framework. (the way I setup my crawlers is just a Python app that does all the thing without YAML configs). Long way ahead!

**Comment by pudo** [comment]
Thanks for trying it out. I know it's a bit complicated as a framework, but the idea is to really pull all the data together into a super-clean set in the end that is easy to program against :) Please let me know if you have questions.

**Comment by quantumchips** [comment]
Sure thanks! Getting the data and shape it the way we want it shouldn't be an issue. I'll have some questions when that's done :) so we'll keep in touch

**Comment by quantumchips** [comment]
I'm trying to push some code in a PR but getting the below error. Is it some access that you can grant me ? 
`remote: No anonymous write access.
fatal: Authentication failed for 'https://github.com/pudo/opensanctions.git/'`

**Comment by pudo** [comment]
Can you maybe start off by making a fork of the repo and pushing to that? 

See here: https://jarv.is/notes/how-to-pull-request-fork-github/

**Comment by quantumchips** [comment]
I actually cloned the repo and I can see it locally in my IDE. I even created a local branch, fixed a typo and tried to push against the `/main` branch. And I got that error.

**Comment by pudo** [comment]
Yes. Pushing to main would put your code live without any quality control, I don't even trust myself to do that most of the time. So the path would be:

* Make a fork on github
* Add that fork as a remote to your local cloned copy 
* Make a branch on your fork 
* Push to the branch
* Create a PR in the github UI. 

Sounds awful, but it's really 4 clicks you get super used to.

**Comment by quantumchips** [comment]
I thought pushing to `main` would trigger some sort of checks and allow you to review the PR before merging! I will work on it locally then and follow your suggested steps :)

**Comment by pudo** [comment]
Inactive; closing.
