### ISSUE TITLE
are the master lists coming back?

### ISSUE THREAD

**Issue by jfaunt** [pudo/opensanctions#17]
Before the system reorganization I was making use of the master lists that were provided. The master lists are still referenced in your FAQs but are no longer available on the site. Is there any plan to bring them back or do I just need to start working with the individual lists on the site? Thanks.

John

**Comment by pudo** [comment]
Well, this has taken a while. The master lists are back in the way they existed previously: as a stacked set of entities from different sources, without merging duplicates. You can fetch them at: 

`https://data.opensanctions.org/datasets/latest/<slug>/entities.ftm.json` 

Where `<slug>` is one of [these collection names](https://github.com/pudo/opensanctions/tree/main/opensanctions/metadata/collections).

Next up: internal de-duplication of these lists. Closing in favour of #86.
