### ISSUE TITLE
Research procurement debarring lists

### ISSUE THREAD

**Issue by pudo** [pudo/opensanctions#3]
Where do they exist? So far, I've seen the World Bank, Moldova. 
- [World bank](http://web.worldbank.org/external/default/main?contentMDK=64069844&menuPK=116730&pagePK=64148989&piPK=64148984&querycontentMDK=64069700&theSitePK=84266)
- US has it all figured out: [Exclusions Extract Data Package](https://www.sam.gov/portal/SAM/?navigationalstate=JBPNS_rO0ABXdcACJqYXZheC5mYWNlcy5wb3J0bGV0YnJpZGdlLlNUQVRFX0lEAAAAAQApdmlldzpmYjMxZGZmOS1lZDVhLTQzOWYtYWE2ZC05NzZmMjBiYzQ2N2EAB19fRU9GX18*&portal:componentId=5c8a0e98-8627-4de4-8635-f9f6b58e3fed&interactionstate=JBPNS_rO0ABXc0ABBfanNmQnJpZGdlVmlld0lkAAAAAQATL2pzZi9uYXZpZ2F0aW9uLmpzcAAHX19FT0ZfXw**&portal:type=action##11)
- [Mexico](http://www01.funcionpublica.gob.mx:8080/SanFicTec/jsp/Ficha_Tecnica/SancionadosN.htm)
- [Moldova](http://tender.gov.md/ro/lista-de-interdictie)
- [Ghana](http://www.ppaghana.org/supbarred.asp) - empty?
- [Russia](http://www.zakupki.gov.ru/epz/dishonestsupplier/dishonestSuppliersQuickSearch/search.html), [Simpler (older?) List](http://rnp.fas.gov.ru/).
- Georgia (.ge): [Blacklist](http://www.procurement.gov.ge/BlackList.aspx), [Warnings](http://www.procurement.gov.ge/WarnedSuppliersRegistry.aspx)
- Brazil: [labour conditions dirty list](http://reporterbrasil.org.br/documentos/lista_06_03_2015.pdf)
- Czech Rep: [unreliable VAT payers](http://adisreg.mfcr.cz/cgi-bin/adis/idph/int_dp_prij.cgi?ZPRAC=FDPHI1&poc_dic=2)

**Comment by kaerumy** [comment]
Only know of Ministry of Housing and Local Government (Malaysia) blacklisted contractors right now:
http://ehome.kpkt.gov.my/index.php/pages/view/43

Translations of the list on the page:

 * Housing developer without license
 * Housing developer found in contempt of the Home Buyers Tribunal
 * Black list of developers that have failed to pay fines
 * Housing developers in failing projects
 * Housing developers involved in failed projects

Sinar's converted it to spreadsheets, we will probably have our own public central database later as we find more blacklisted developers for Malaysia for own use and others.

**Comment by pudo** [comment]
thanks, @kaerumy - that's very cool. Please keep me updated with regards to the database you're building!

**Comment by benparkergit** [comment]
UN Development Programme: 

http://www.undp.org/content/undp/en/home/operations/procurement/business/protest-and-sanctions/ineligibility-list/

Do you want this scraped?

**Comment by benparkergit** [comment]
UNOPS: https://www.unops.org/english/Opportunities/suppliers/Pages/Vendor-sanctions.aspx

**Comment by pudo** [comment]
@benparkergit sorry saw this pretty late! That looks amazing, if you felt up for a scraper it'd make a cool contribution!

**Comment by SERutherford** [comment]
Here is Brazil's consolidated state procurement debarment list: http://www.portaltransparencia.gov.br/ceis/
...and as downloadable data: http://www.portaltransparencia.gov.br/downloads/ under "Sanções" (sanctions).

**Comment by SERutherford** [comment]
Panama's list of government procurement debarments: http://panamacompra.gob.pa/portal/EmpresasInhabilitadas.aspx

**Comment by SERutherford** [comment]
Bangladesh debarment list: https://www.eprocure.gov.bd/resources/common/DebarmentRpt.jsp

**Comment by SERutherford** [comment]
Norway's state-run Norges Bank has a list of excluded companies from receiving any state investment: https://www.nbim.no/en/responsibility/exclusion-of-companies/

**Comment by SERutherford** [comment]
U.S. H-1B Debarred/Disqualified List of Employers: https://www.dol.gov/whd/immigration/H1BDebarment.htm

**Comment by DavidLemayian** [comment]
There's a useful list of debarred and conditional-barred firms from World Bank and cross-debarment between World Bank, Asian Development Bank, European Bank for Reconstruction and Development, Inter-American Development Bank, and African Development Bank.

http://www.worldbank.org/en/projects-operations/procurement/debarred-firms

**Comment by pudo** [comment]
Ok, since we have included all the international development bank lists (cf. https://www.opensanctions.org/datasets/debarment/ ), I'm closing this. Need to think about how to approach national-level datasets, still.
