### ISSUE TITLE
French sanction list

### ISSUE THREAD

**Issue by ilanoh** [pudo/opensanctions#62]
Hello,

How can I contribute to integrate the french sanction list ?

It can be downloaded from this url in a zip that contains an excel file.

https://www.tresor.economie.gouv.fr/services-aux-entreprises/sanctions-economiques/tout-savoir-sur-les-personnes-et-entites-sanctionnees

**Comment by sunu** [comment]
Hi @ilanoh, that looks like a useful source to scrape. We integrate individual sources by writing scrapers using the [Memorious](https://memorious.readthedocs.io/en/latest/) toolkit. Would you be interested in writing a scraper for this?

**Comment by ilanoh** [comment]
Hello @sunu, Yes, I will check the documentation for Memorious, I never done it before, if I'm stuck I will come leave a message here.

**Comment by sunu** [comment]
@ilanoh Awesome! If you need examples, take a look at these directories -- https://github.com/alephdata/opensanctions/tree/master/opensanctions/crawlers for the Python part of crawlers and https://github.com/alephdata/opensanctions/tree/master/opensanctions/config for the yaml configurations.

**Comment by ang-st** [comment]
I'm also interested :)

@sunu I have already a scraper (not with memorius), the things is this list is published as a **xlsx** file (!). 
Is it ok to add dependencies like [openpyxl](https://openpyxl.readthedocs.io/en/stable/) ?  
I initially used pandas but we could stretch this down to  something with a lower footprint

**Comment by sunu** [comment]
@ang-st We generally use `xlrd` for that. Here's an example from the Austrialian sanctions scraper: https://github.com/alephdata/opensanctions/blob/master/opensanctions/crawlers/au_dfat_sanctions.py#L70

**Comment by ang-st** [comment]
@sunu thanks for the pointer, we'll start from there

**Comment by sunu** [comment]
`xlrd` dropped `xlsx` support in the latest release. We'll have to use `openpyxl` as you suggested earlier.

**Comment by ang-st** [comment]
Thanks for the info.

The "Gel des avoirs" listing will offer a JSON and XML API starting january
see [announcement](https://www.tresor.economie.gouv.fr/Articles/2020/12/07/refonte-du-registre-national-des-gels)

@TheophileDiot and I already checked data format and we will be able to update the P/R accordingly once the api is live

**Comment by ilanoh** [comment]
@ang-st I have the json and xml file already

How can I share them ?

**Comment by pudo** [comment]
@ilanoh I can't quite decipher the treasury page... Do you know what base domain for the API endpoint they describe is?

**Comment by ang-st** [comment]
@pudo i asked the very same question to the administration something like 2 weeks ago, and they said they'll update with `base url` once the service is up and running.
BTW i'm on their mailing list so i guess i'll have the announcement right into my mailbox.

For now, they still update the docx file as implemented in https://github.com/alephdata/opensanctions/pull/64

**Comment by ang-st** [comment]
Here are the relevant infos for API :  
Launching date 2021-03-16
public url : https://gels-avoirs.dgtresor.gouv.fr/
