### ISSUE TITLE
Council of Europe - coe_assembly crawler URL give 404 - not found

### ISSUE THREAD

**Issue by SarunasCard** [pudo/opensanctions#83]
Hello,
Council of Europe - coe_assembly crawler URL is invalid. Past few days is returning 404 - not found. Hope this will help spot outdated resources.

**Comment by pudo** [comment]
Thanks for the heads-up. Looks like the made a whole new web site, so it's effectively going to be a new scraper. But PACE has been a hotbed of corruption, so I guess we gotta do :)
